"""OpenAI Sora video generation.

Simplified for the upload-first workflow: generates a single video clip
as fallback when Veo fails or budget prefers Sora.
"""

import asyncio
import base64
import time
from pathlib import Path

import httpx
from openai import OpenAI
from rich.console import Console

from config import settings
from utils.cost_tracker import CostTracker
from utils.retry import retry_async

console = Console()


class SoraGenerator:
    """Generates a single video clip using OpenAI Sora."""

    def __init__(self, quality: str = None):
        self.quality = quality or settings.VIDEO_QUALITY
        self.client = OpenAI(api_key=settings.OPENAI_API_KEY)
        self.cost_tracker = CostTracker()

    async def generate_clip(
        self, prompt: str, reference_image_path: str | None, output_name: str
    ) -> str | None:
        """
        Generate a single video clip.

        Args:
            prompt: The cinematic video generation prompt
            reference_image_path: Path to hero photo for image-to-video
            output_name: Base name for output file

        Returns:
            Path to generated clip, or None on failure
        """
        if not self.cost_tracker.can_afford("sora", self.quality):
            console.print("[yellow]Budget exceeded — cannot generate Sora clip[/yellow]")
            return None

        console.print("[cyan]Generating Sora clip...[/cyan]")

        try:
            clip_path = await self._generate(prompt, reference_image_path, output_name)

            if clip_path:
                clip_dur = settings.CLIP_DURATION["sora"]
                cost = clip_dur * settings.COST_PER_SECOND["sora"][self.quality]
                self.cost_tracker.record_cost(
                    vehicle_id=0,
                    engine="sora",
                    quality=self.quality,
                    duration=clip_dur,
                    cost=cost,
                    call_type="video_generation",
                )
                console.print(f"[green]Sora clip saved: {Path(clip_path).name}[/green]")

            return clip_path

        except Exception as e:
            console.print(f"[red]Sora generation failed: {e}[/red]")
            return None

    @retry_async(max_retries=3, base_delay=5.0, max_delay=60.0, operation_name="Sora clip generation")
    async def _generate(
        self, prompt: str, reference_image_path: str | None, output_name: str
    ) -> str | None:
        """Generate clip with retry logic."""
        input_parts = [{"type": "text", "text": prompt}]

        if reference_image_path and Path(reference_image_path).exists():
            image_data = Path(reference_image_path).read_bytes()
            b64_image = base64.b64encode(image_data).decode()
            input_parts.insert(0, {
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{b64_image}"},
            })

        response = self.client.responses.create(
            model="sora",
            input=input_parts,
            tools=[{
                "type": "video_generation",
                "aspect_ratio": settings.VIDEO_ASPECT_RATIO,
                "duration": settings.CLIP_DURATION["sora"],
            }],
        )

        console.print("[dim]Waiting for Sora generation...[/dim]")
        video_url = None
        max_wait = 300
        start = time.time()

        while time.time() - start < max_wait:
            result = self.client.responses.retrieve(response.id)
            for out in result.output:
                if out.type == "video_generation_call" and hasattr(out, "video_url"):
                    video_url = out.video_url
                    break
            if video_url:
                break
            await asyncio.sleep(10)

        if not video_url:
            console.print("[red]No video generated by Sora[/red]")
            return None

        output_path = settings.VIDEOS_DIR / f"{output_name}_clip.mp4"
        async with httpx.AsyncClient() as http_client:
            video_response = await http_client.get(video_url)
            video_response.raise_for_status()
            output_path.write_bytes(video_response.content)

        return str(output_path)
